proxy-server:
  host: "127.0.0.1"
  port: ":25565"
  debug: false
  timeout: 15 #Doesn't do anything rn
  protocol:
    AvailableProtocols: [] #Doesn't do anything rn
server:
  ip: "127.0.0.1"
  port: ":25567"
performance: #Change me!
   cpu: 0 #0 = all cores
   gc-percent: 100 #Not implemented
   check-server-per-tick: 20 #TBD
   packets-per-second: 0 #TBD
   movement-checks: false #TBD
   limbo-mode-when-backend-down: false #TBD
   check-server-seconds: 1 #Change this one for connecting to the backend server
   listeners: 4
