proxy-server:
  host: "127.0.0.1:25565"
  debug: false
  timeout: 15 #Doesn't do anything rn
  protocol:
    AvailableProtocols: [] #Doesn't do anything rn
backends:
  servers: ["192.168.88.56:25565","127.0.0.1:25567"] #First server in list is the one that it will connect to first //,"127.0.0.1:25567"
  load-balancing-servers: [] #Enter the array number in the list above that you want to load balance
  load-balancing-type: "none" #
performance: #Change me!
   cpu: 0 #0 = all cores
   gc-percent: 100
   packets-per-second: 200
   movement-checks: false #TBD
   limbo-mode-when-backend-down: false #Keep clients connected until backed recovers
   check-server-seconds: 1 #Change this one for connecting to the backend server
   listeners: 4
