name: HoneySmoke

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.2

    - name: Tidy
      run: go mod tidy
      
    - name: BuildLinux
      run: go build -o ~/HoneySmoke-Linux/ -v ./...
      
    - name: BuildWindows
      run: env GOOS=windows GOARCH=amd64 go build -o ~/HoneySmoke-Windows/ -v ./...
        
    - name: CopyConfigLinux
      run: cp ./config.yml ~/HoneySmoke-Linux/
      
    - name: CopyConfigWindows
      run: cp ./config.yml ~/HoneySmoke-Windows/
    
    - name: Test
      run: go test -v ./...
    
    - name: Upload Linux Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: HoneySmoke-Linux # optional, default is artifact
         # A file, directory or wildcard pattern that describes what to upload
        path: ~/HoneySmoke-Linux/
        if-no-files-found: error
        
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: HoneySmoke-Windows # optional, default is artifact
         # A file, directory or wildcard pattern that describes what to upload
        path: ~/HoneySmoke-Windows/
        if-no-files-found: error
